Databaseinert
misterorora/to-do-list pull request #29
Opened 2023-05-09 08:36 UTC by misterorora

updated Database class

2023-05-09 11:12 UTC, JonasLiendl requested changes
Habe noch ein paar Sachen die man verbessern könnte. Außerdem ist die Klasse noch nicht ganz fertig, oder?

2023-05-09 11:12 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +        PreparedStatement pstmt = null;
```suggestion
        PreparedStatement pstmt;
```

2023-05-09 11:12 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            String sql = "INSERT INTO projects(title, description, dateTimeCreated, dateTimeDeadline, ownerId) VALUES (?,?,?,?,?)";
```suggestion
            String sql = "INSERT INTO projects (title, description, dateTimeCreated, dateTimeDeadline, ownerId) VALUES (?,?,?,?,?)";
```

2023-05-09 11:12 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +        PreparedStatement pstmt = null;
Name ist meiner Ansicht nach nicht direkt ersichtlich. Ändern?

2023-05-09 11:12 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +        PreparedStatement pstmt = null;
Name
+
```suggestion
        PreparedStatement pstmt;
```

2023-05-09 11:12 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            String sql = "INSERT INTO tasks(description, status, priority, dateTimeCreated, dateTimeDone, dateTimePlannedStart, dateTimePlannedEnd, dateTimeDeadline, projectId) VALUES (?,?,?,?,?,?,?,
```suggestion
            String sql = "INSERT INTO tasks (description, status, priority, dateTimeCreated, dateTimeDone, dateTimePlannedStart, dateTimePlannedEnd, dateTimeDeadline, projectId) VALUES (?,?,?,?,?,?,?,?,?)";
```

2023-05-09 11:12 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +        PreparedStatement pstmt = null;
Name + 
```suggestion
        PreparedStatement pstmt;
```

2023-05-09 11:12 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +        PreparedStatement pstmt = null;
Name +
```suggestion
        PreparedStatement pstmt;
```

2023-05-09 11:24 UTC, misterorora commented on src/main/java/hwr/oop/application/Database.java
> +        // String sqlFile = "/src/database/sql.sql"; //path to SQL file
> Habe noch ein paar Sachen die man verbessern könnte. Außerdem ist die Klasse noch nicht ganz fertig, oder?

Du hast Recht, mir ist auch gerade aufgefallen das unser Select fehlt. Mach ich fix, vergesse ich noch etwas?

2023-05-09 11:25 UTC, misterorora commented on src/main/java/hwr/oop/application/Database.java
> +        // String sqlFile = "/src/database/sql.sql"; //path to SQL file
> Kommentare benötigt?

Nicht unbedingt, würde nur irgendwo gerne die Pfade abelegt haben.

2023-05-09 11:26 UTC, misterorora commented on src/main/java/hwr/oop/application/Database.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"); //"Year-Month-Day-"T"-Hour-Minute-Second-Timezone-"Z"
> Ist ISO-Format nicht schon direkt in Java implementiert?

Das Problem ist eher SQLite, was mit dem Datentyp LocalDateTime nichts anfangen kann --> damit übergeben wir das Datenformat LocalDateTime als String der SQL Datenbank

2023-05-09 11:26 UTC, misterorora commented on src/main/java/hwr/oop/application/Database.java
> +    public String dateTimeConvertToString(LocalDateTime time) {  //no LocalDateTime datatype in sqllite, need to convert to String
> Extra Klasse?

hab ich auch schon gedacht, in Application?

2023-05-10 07:16 UTC, misterorora reviewed
commited review of Jonas

2023-05-10 08:17 UTC, misterorora commented
Habe einmal die Changes durchgeführt -- Select Methode ist drin, Variablen sind umbenannt.

2023-05-10 10:41 UTC, JonasLiendl requested changes

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +        Connection connectionToDatabase = null;
`conn` hätte auch bleiben können, oder `connection`. Dass man zur Datenbank verbinden möchte geht schon aus dem Kontext der Methode hervor.

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +    public void insertIntoProject(String title, String description, LocalDateTime dateTimeCreated, LocalDateTime dateTimeDeadline, int ownerId) {
```suggestion
    public void insertIntoProject(Project project) {
```
Viele Parameter machen Code unübersichtlich. Da das alles Attribute von dem Object `Project` sind, kann man auch zu `Project project` kürzen, und die einzelnen Attribute mit den Gettern abfragen.

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(1, title);
```suggestion
            preparedStatement.setString(1, project.getTitle());
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(2, description);
```suggestion
            preparedStatement.setString(2, project.getDescription());
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(3, formatToString.format(dateTimeCreated));
```suggestion
            preparedStatement.setString(3, formatToString.format(project.getDateTimeCreated()));
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(4, formatToString.format(dateTimeDeadline));
```suggestion
            preparedStatement.setString(4, formatToString.format(project.getDeadline()));
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setInt(5, ownerId);
```suggestion
            preparedStatement.setInt(5, project.getOwnerID());
```
Methode muss noch implementiert werden. Soll mit dem ID Issue kommen.

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +    public void insertIntoTasks(String description, int status, int priority, LocalDateTime dateTimeCreated, LocalDateTime dateTimeDone, LocalDateTime dateTimePlannedStart, LocalDateTime dateTimePlan
```suggestion
    public void insertIntoTasks(Task task) {
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(1, description);
```suggestion
            preparedStatement.setString(1, task.getDescription());
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setInt(2, status);
```suggestion
            preparedStatement.setInt(2, task.getStatus());
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setInt(3, priority);
```suggestion
            preparedStatement.setInt(3, task.getPriority());
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(4, formatToString.format(dateTimeCreated));
```suggestion
            preparedStatement.setString(4, formatToString.format(task.getDateTimeCreated()));
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(5, formatToString.format(dateTimeDone));
```suggestion
            preparedStatement.setString(5, formatToString.format(task.getDateTimeDone()));
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(6, formatToString.format(dateTimePlannedStart));
```suggestion
            preparedStatement.setString(6, formatToString.format(task.getDateTimePlannedStart()));
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(7, formatToString.format(dateTimePlannedEnd));
```suggestion
            preparedStatement.setString(7, formatToString.format(task.getDateTimePlannedEnd()));
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(8, formatToString.format(dateTimeDeadline));
```suggestion
            preparedStatement.setString(8, formatToString.format(task.getDateTimeDeadline()));
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setInt(9, projectId);
```suggestion
            preparedStatement.setInt(9, task.getProject().getID());
```
Methode für getID muss noch implementiert werden.

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +    public void insertIntoTags(String title) {
```suggestion
    public void insertIntoTags(Tag tag) {
```

2023-05-10 10:41 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/Database.java
> +            preparedStatement.setString(1, title);
```suggestion
            preparedStatement.setString(1, tag.getTitle());
```

2023-05-10 13:58 UTC, misterorora commented on src/main/java/hwr/oop/application/Database.java
> +        Connection connectionToDatabase = null;
Wie gesagt, das war auf wunsch von Stefan so... kam nicht von mir 😅

2023-05-10 14:07 UTC, misterorora reviewed
👍🏽

2023-05-11 05:02 UTC, JonasLiendl approved these changes

2023-05-11 05:18 UTC, merged