Project Console
misterorora/to-do-list pull request #30
Opened 2023-05-09 08:45 UTC by paulstober20

2023-05-09 11:27 UTC, JonasLiendl requested changes
Tests sind soweit ich gesehen habe ganz gut, aber ich habe noch ein paar Änderungen für Namen und Kleinigkeiten.

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +    private static final String FORMAT = "yyyy-MM-dd";
```suggestion
    private static final String DATE_FORMAT = "yyyy-MM-dd";
```
Klarer Name

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +    ProjectBuilder newProject = new ProjectBuilder();
```suggestion
    ProjectBuilder projectBuilder = new ProjectBuilder();
```
Passender Name

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +    ConsoleColors colors = new ConsoleColors();
```suggestion

```
Nicht benötigt, da mit `ConsoleColors.*` die einzelnen Variablen erreicht werden können (Verhalten wie ein Enum). Außerdem wird das ganze Fehler werfen, wenn es in den main-branch gemerged wird, da der Konstruktor für die Klasse nun private ist, um genau das zu verhinden.

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        title += inputStream.nextLine();
```suggestion
        title = inputStream.nextLine();
```
Soll die neue Eingabe an die bereits gespeicherte Variable angehanden werden, oder nicht?

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(FORMAT);
```suggestion
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_FORMAT);
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        outputStream.println("Please enter the deadline of the project(optional)(format yyyy-MM-dd):");
```suggestion
        outputStream.println("Please enter a deadline for the project (optional)(format yyyy-MM-dd):");
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        }else {
```suggestion
        } else {
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        outputStream.println(colors.ANSI_CYAN + "Add new Project" + colors.ANSI_RESET);
```suggestion
        outputStream.println(ConsoleColors.ANSI_CYAN + "Add new Project" + ConsoleColors.ANSI_RESET);
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        newProject.setTitle(addNewTitle());
```suggestion
        projectBuilder.setTitle(addNewTitle());
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        newProject.setDescription(addNewDescription());
```suggestion
        projectBuilder.setDescription(addNewDescription());
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        newProject.setDeadline(addNewDeadline());
```suggestion
        projectBuilder.setDeadline(addNewDeadline());
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        return newProject.build();
```suggestion
        return projectBuilder.build();
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        newProject.setTitle(addNewTitle());
Kann auch mit `projectBuilder.setTitle(addNewTitle()).setDescription(addNewDescription()).setDeadline(addNewDeadline()).build()` hintereinander geschrieben werden.

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddTaskConsole.java
> +    private static final String FORMAT = "yyyy-MM-dd";
```suggestion
    private static final String DATE_FORMAT = "yyyy-MM-dd";
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddTaskConsole.java
> +            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(FORMAT);
```suggestion
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_FORMAT);
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddTaskConsole.java
> +            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(FORMAT);
```suggestion
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_FORMAT);
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddTaskConsole.java
> +            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(FORMAT);
```suggestion
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_FORMAT);
```

2023-05-09 11:27 UTC, JonasLiendl commented on src/test/java/hwr/oop/application/console/AddProjectConsoleTest.java
> +        String expectedOutput = "Please enter the deadline of the project(optional)(format yyyy-MM-dd):";
```suggestion
        String expectedOutput = "Please enter a deadline for the project(optional)(format yyyy-MM-dd):";
```

2023-05-09 11:29 UTC, JonasLiendl commented
Es gibt bei dem Branch auch Merge-Konflikte. Bitte beheben.

2023-05-09 11:32 UTC, JonasLiendl commented
Es gibt bei dem Branch auch Merge-Konflikte. Bitte beheben.

2023-05-09 12:36 UTC, paulstober20 commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +        title += inputStream.nextLine();
Das muss sein, weil es sonst nicht möglich wäre Leerzeichen einzugeben.

2023-05-11 05:01 UTC, JonasLiendl approved these changes

2023-05-11 05:18 UTC, merged