Changed to local date time
misterorora/to-do-list pull request #64
Opened 2023-06-10 13:07 UTC by misterorora

Viele Changes, bitte approven oder ablehnen...

2023-06-10 15:29 UTC, JonasLiendl requested changes
Bitte nochmal meine Kommentare durchgehen und die Namen von Variablen bei denen der Typ `LocalDateTime` zu `LocalDate` geändert wurde, zu `date...` umbenennen (am besten in der IDE, dann gibt es kein Code Massaker).

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/database/services/ProjectService.java
> +import java.time.LocalDate;
```suggestion
```

2 identische imports

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/database/services/TaskService.java
> +import java.time.LocalDate;
```suggestion
```

2 identische imports

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/helper/DateConverter.java
> +    public static String convertToString(LocalDate dateTime) {
Zu einer Variable mit Typ Temporal zusammenfügen?

Dann Typ der Instanz checken, validieren und zurückgeben.

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/Project.java
>  import java.time.LocalDateTime;
```suggestion
```

Wird nicht benutzt?

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/Project.java
> +    private final LocalDate dateTimeCreated;
```suggestion
    private final LocalDate dateCreated;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/Project.java
> +    private LocalDate dateTimeDeadline;
```suggestion
    private LocalDate dateDeadline;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/Project.java
>          this.dateTimeDeadline = deadline;
```suggestion
        this.dateDeadline = deadline;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/Project.java
> +        this.dateTimeCreated = LocalDate.now();
```suggestion
        this.dateCreated = LocalDate.now();
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/Project.java
>          this.dateTimeDeadline = deadline;
```suggestion
        this.dateDeadline = deadline;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/Project.java
> +    public LocalDate getDateTimeCreated() {
```suggestion
    public LocalDate getDateCreated() {
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/Project.java
>          return this.dateTimeCreated;
```suggestion
        return this.dateCreated;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/Project.java
>          return this.dateTimeDeadline;
```suggestion
        return this.dateDeadline;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/project/ProjectBuilder.java
>  import java.time.LocalDateTime;
```suggestion
```

Unbenutzt?

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddTaskConsole.java
> +import java.time.LocalDate;
```suggestion
```

2 identische imports

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/application/console/AddProjectConsole.java
> +import java.time.LocalDate;
```suggestion
```

2 identische imports

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
> +    private LocalDate dateTimePlannedStart;
```suggestion
    private LocalDate datePlannedStart;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
> +    private LocalDate dateTimePlannedEnd;
```suggestion
    private LocalDate datePlannedEnd;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
> +    private LocalDate dateTimeDeadline;
```suggestion
    private LocalDate dateDeadline;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
> +            LocalDate dateTimeDeadline,
```suggestion
            LocalDate dateDeadline,
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
> +            LocalDate dateTimePlannedEnd
```suggestion
            LocalDate datePlannedStart,
            LocalDate datePlannedEnd
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
>      }
Würde `datePlannedEnd - datePlannedStart` nicht auch die Differenz der Tage darstellen?

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
> +
```suggestion
    public long getUntilDateDeadline(){
        LocalTime time = LocalTime.of(0, 0, 0);
        LocalDateTime ldtDeadline = LocalDateTime.of(this.dateTimeDeadline, time);
        Duration difference = Duration.between(LocalDateTime.now(), ldtDeadline);
        return difference.toDays();

```
Hier das gleiche.

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
>          return this.dateTimePlannedStart;
```suggestion
    public LocalDate getDatePlannedStart() {
        return this.datePlannedStart;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
>          return this.dateTimePlannedEnd;
```suggestion
    public LocalDate getDatePlannedEnd() {
        return this.datePlannedEnd;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
>          return this.dateTimeDeadline;
```suggestion
    public LocalDate getDateDeadline() {
        return this.dateDeadline;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
>          this.dateTimePlannedEnd = endDate;
```suggestion
    public void changePlannedDate(LocalDate startDate, LocalDate endDate) {
        this.datePlannedStart = startDate;
        this.datePlannedEnd = endDate;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/Task.java
>          this.dateTimeDeadline = dateTimeDeadline;
```suggestion
    public void changeDateDeadline(LocalDate dateDeadline) {
        this.dateDeadline = dateDeadline;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/TaskBuilder.java
> +import java.time.LocalDate;
```suggestion
```

2 identische imports

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/TaskBuilder.java
> +    private LocalDate dateTimeDeadline;
```suggestion
    private LocalDate dateDeadline;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/TaskBuilder.java
> +    private LocalDate dateTimePlannedEnd;
```suggestion
    private LocalDate datePlannedStart;
    private LocalDate datePlannedEnd;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/TaskBuilder.java
>          this.dateTimeDeadline = dateTimeDeadline;
```suggestion
    public TaskBuilder setDateDeadline(LocalDate dateDeadline) {
        this.dateDeadline = dateDeadline;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/main/java/hwr/oop/task/TaskBuilder.java
>          this.dateTimePlannedEnd = dateTimeEnd;
```suggestion
    public TaskBuilder setDatePlanned(LocalDate dateStart, LocalDate dateEnd) {
        this.datePlannedStart = dateStart;
        this.datePlannedEnd = dateEnd;
```

2023-06-10 15:29 UTC, JonasLiendl commented on src/test/java/hwr/oop/helper/DateConverterTest.java
> +import java.time.LocalDate;
```suggestion
```

2 identische imports

2023-06-10 15:29 UTC, JonasLiendl commented on src/test/java/hwr/oop/project/ProjectTest.java
>  import java.time.LocalDateTime;
```suggestion
```

unbenutzt?

2023-06-10 15:29 UTC, JonasLiendl commented on src/test/java/hwr/oop/task/TaskGetterTest.java
>  import java.time.LocalDateTime;
Importiert, aber nichts am Code verändert? Tests laufen noch immer mit LocalDateTime => LocalDate wird nicht verwendet?

2023-06-10 15:29 UTC, JonasLiendl commented on src/test/java/hwr/oop/task/TaskMethodTest.java
> +        */
Wenn Test nicht mehr verwendet wird, bitte löschen, oder als veraltet markieren, aber nicht auskommentieren.

2023-06-10 15:29 UTC, JonasLiendl commented on src/test/java/hwr/oop/testDatabase/testDatabase.db
Bitte die ganzen .db Dateien in die `.gitignore` packen, wenn sie nicht hochgeladen werden sollen (es sei denn sie sind relevant, damit der Code funktioniert).

2023-06-11 08:05 UTC, misterorora commented on src/main/java/hwr/oop/task/Task.java
>      }
Habe es gerade gestestet, scheint nicht so zu sein. 
Es gibt allerdings von LocalDate eine eigene Methode. Die hatte gestern allerdings immer Fehler geschmissen wegen verschiedenster Gründen, weswegen wir uns dann hierzu entschieden hatten.

2023-06-11 08:18 UTC, misterorora commented on src/test/java/hwr/oop/task/TaskGetterTest.java
>  import java.time.LocalDateTime;
Ja, ist richtig! 
LocalDate kann hier raus.

2023-06-11 08:35 UTC, misterorora commented
Hab die Changes commited.

2023-06-11 09:19 UTC, MuffinCPT approved these changes

2023-06-11 09:20 UTC, merged